backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('table/', include("table.urls")),
    path('user/', include("user.urls")),
    path('', include("index.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/user/urls.py
from django.urls import path
from .views import ReceptionView, add_customers, success_view

app_name = 'user'

urlpatterns = [
    path('reception/', ReceptionView.as_view(), name="reception"),
    path('add_customers/', add_customers, name="add_customers"),
    path('success/<int:group_id>/', success_view, name='success_url'), 
]

backend/user/models.py
from django.db import models
from table.models import Table
from django.utils.translation import gettext_lazy as _

class Customer(models.Model):
    id = models.AutoField(primary_key=True)
    people = models.IntegerField(null=True, blank=True, verbose_name=_("people"))
    date = models.DateField(null=True, blank=True, verbose_name=_("date"))
    check_in_time = models.TimeField(null=True, blank=True, auto_now_add=True, verbose_name=_("check_in_time"))
    check_out_time = models.TimeField(null=True, blank=True, verbose_name=_("check_out_time"))
    stay_time = models.TimeField(null=True, blank=True, verbose_name=_("stay_time"))
    
    table_id = models.ForeignKey(Table, verbose_name=_("table_id"), on_delete=models.CASCADE)

    class Meta:
        db_table = 'customer'
    
    def __str__(self):
        return f'Customer {self.id}'

    @classmethod
    def get_next_group_id(cls):
        last_customer = cls.objects.all().order_by('id').last()
        if not last_customer:
            return 1
        return last_customer.id + 1

backend/user/forms.py
from django import forms
from .models import Customer, Table


class CustomerGroupForm(forms.Form):
    people = forms.IntegerField(
        label="顧客数",
        min_value=1,
        widget=forms.NumberInput(attrs={
            'class': 'spinner',
            'min': '1',
            'max': '40',
            'value': '1'
        })
    )

backend/user/views.py
from django.shortcuts import render,  redirect
from django.urls import reverse
from django.utils import timezone
from django.views.generic import DetailView, ListView, CreateView, TemplateView
from django.contrib import messages
from .forms import CustomerGroupForm
from .models import Customer
from table.models import Table
from django.db import transaction
import joblib
import numpy as np
from datetime import datetime, timedelta

class ReceptionView(TemplateView):
    template_name = 'user/reception.html'


# 保存したモデルとスケーラーの読み込み
model = joblib.load('./models/izakaya_stay_time_predictor.pkl')
scaler = joblib.load('./models/scaler.pkl')

# 新しいデータでの予測関数
def predict_stay_time(checkIn_hours, member, week, month, day):
    data = np.array([[checkIn_hours, member, week, month, day]])
    data_scaled = scaler.transform(data)
    predicted_time = model.predict(data_scaled)
    return predicted_time[0]


def add_customers(request):
    if request.method == "POST":
        form = CustomerGroupForm(request.POST)
        if form.is_valid():
            date = timezone.now().date()
            check_in_time = timezone.now().time()
            people = form.cleaned_data['people']

            available_tables = Table.objects.filter(status='o').order_by('max_seats')
            if not available_tables.exists():
                messages.error(request, '利用可能なテーブルがありません。')
                return redirect('user:add_customers')

            remaining_customers = people
            selected_tables = []

            def get_table_for_customers(num):
                table = available_tables.filter(max_seats=num).first()
                if table:
                    available_tables.filter(id=table.id).update(status='x')
                    return table
                return None

            # 優先される席
            table_map = {
                1: [1],
                2: [2],
                3: [4],
                4: [4],
                5: [10],
                6: [10],
                7: [10],
                8: [10],
                9: [10],
                10: [10]
            }

            while remaining_customers > 0:
                table_size_options = table_map.get(remaining_customers, [])
                if not table_size_options:
                    table_size_options = [10]  # Default to 10 if no specific size found

                table_found = False
                for size in table_size_options:
                    table = get_table_for_customers(size)
                    if table:
                        selected_tables.append(table)
                        remaining_customers -= table.max_seats
                        table_found = True
                        break

                if not table_found:
                    next_smaller_size = remaining_customers // 2
                    for size in range(next_smaller_size, 0, -1):
                        table = get_table_for_customers(size)
                        if table:
                            selected_tables.append(table)
                            remaining_customers -= table.max_seats
                            table_found = True
                            break

                if not table_found:
                    messages.error(request, '十分な席数がありません。')
                    return redirect('user:add_customers')

            try:
                with transaction.atomic():
                    check_in_hours = check_in_time.hour
                    week = date.weekday()  # 0: Monday, ..., 6: Sunday
                    month = date.month
                    day = date.day

                    predicted_stay_time = predict_stay_time(check_in_hours, people, week, month, day)

                    for table in selected_tables:
                        Customer.objects.create(
                            people=min(table.max_seats, people),
                            date=date,
                            check_out_time=None,
                            stay_time=timedelta(minutes=predicted_stay_time)+datetime.now(),  # 予測された滞在時間を追加
                            table_id=table
                        )

                    messages.success(request, '顧客が正常に追加されました。')
                    return redirect(reverse('user:success_url', kwargs={'group_id': selected_tables[0].id}))

            except Exception as e:
                messages.error(request, f'エラーが発生しました: {str(e)}')
                return redirect('user:add_customers')

    else:
        form = CustomerGroupForm()

    return render(request, 'user/add_customers.html', {'form': form})

def success_view(request, group_id):
    return render(request, 'user/success.html', {'group_id': group_id})

backend/templates/user/add_customers.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div class="customer-wrap">
    <div class="hoge">
        <h2>人数を入力してください</h2>
        <form id="myform" method="post">
            {% csrf_token %}
            <div class="spinner-container">
                <span class="spinner-sub disabled">-</span>
                {% for field in form %}
                    {{ field }}
                {% endfor %}
                <span class="spinner-add">+</span>
            </div>
            <div class="hoge_button">
                <button type="submit" form="myform" class="btn2">確定</button>
            </div>
        </form>
    </div>
</div>
{% endblock  %}
{% block js %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="{% static "js/script.js" %}"></script>
{% endblock  %}

backend/templates/user/reception.html
{% extends "base.html" %}
{% block content %}
<div id="bird"></div>
<div class="hoge_button">
    <a href="{% url "user:add_customers" %}" class="btn"><p class="reception">受付開始</p></a>
</div>
{% endblock %}

{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r121/three.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vanta@latest/dist/vanta.birds.min.js"></script>
<script>
VANTA.BIRDS({
    el: "#bird",
    mouseControls: true,
    touchControls: true,
    gyroControls: false,
    minHeight: 500.00,
    minWidth: 200.00,
    scale: 1.00,
    scaleMobile: 1.00,
    backgroundColor: 0xffffff,
    color1: 0x69ff,
    color2: 0xcedd2,
    colorMode: "lerpGradient",
    birdSize: 2.00,
    separation: 31.00
})
</script>
{% endblock %}

backend/templates/user/success.html
{% extends "base.html" %}
{% block content %}
<div class="guidance">
    <h2>番号の席にお進みください。</h2>
    <h1>{{ group_id }}</h1>
</div>
{% endblock %}

{% block js %}
{% comment %} <script type="text/javascript">
    // 5秒後にリダイレクト
    setTimeout(function(){
        window.location.href = "{% url 'user:reception' %}";
    }, 5000);
</script> {% endcomment %}
{% endblock %}